### ISSUE TITLE
RegEx of Pattern attribute

### ISSUE THREAD

**Issue by robsonsobral** [cferdinandi/bouncer#1]
Hi!

Do you forgive me for not submit a test case? This is a matter of documentation.

The native validation of the `pattern` attribute modifies its value a little, before test it.

Shouldn't it be something like `'^(?:' + field.getAttribute('pattern') + ')$'` to respect the same rules?

---

I'm sorry for being the first annoying guy to open an issue.

**Comment by cferdinandi** [comment]
I'm so sorry, but it's no clear to me what you're trying to say. Have you tested it? The demo page uses on-page `patterns` and it works as-is.

**Comment by robsonsobral** [comment]
I'm sorry, mister. My bad.

I think, despite you have give up on using the native API, the validation has to be the same.

From the [specification](https://www.w3.org/TR/html51/sec-forms.html#the-pattern-attribute):

> [...] the regular expression language used for this attribute is the same as that used in JavaScript, except that the pattern attribute is matched against the entire value, not just any subset (somewhat as if it implied a `^(?:` at the start of the pattern and a `)$` at the end). 

Which makes the `^` and `$` on some [demo samples](https://cferdinandi.github.io/bouncer/) unnecessary and allows some [pattern mismatches](https://www.w3.org/TR/html51/sec-forms.html#suffer-from-a-pattern-mismatch). For example, [your demo of the telephone number](https://cferdinandi.github.io/bouncer/#tel), matches `123-456-7890`, but also `00000000000000123-456-7890`, `ABCD123-456-7890` or `123-456-7890-this RegEx's start isn't anchored to the start of the string neither its end is anchored to the end of the string`.

There's still the case of the `multiple` attribute, which requires the RegEx to be tested on each value and the RegEx flag:

> [..] compiled as a JavaScript regular expression with only the "u" flag specified [...]

I can submit a pull request, if you want to.

**Comment by robsonsobral** [comment]
@cferdinandi , may I add the [lock](https://docs.npmjs.com/files/package-lock.json) and changelog files?

**Comment by robsonsobral** [comment]
Wow, I wasn't talking about the release, but something to help others of analyze the changes in the future. It can be useful.

---

Pull request submitted!

**Comment by cferdinandi** [comment]
Fixed with v1.0.3. thanks for this, @robsonsobral !
