### ISSUE TITLE
Doesn't work with inputs containing square brackets [ ] in the name

### ISSUE THREAD

**Issue by smcyr** [cferdinandi/bouncer#10]
When the inputs contain square brackets [ ] (ex: `<input type="email" name="ContactForm[email]">`), it creates a duplicated error message each time the input is validated. In the code, `field.form.querySelectorAll('[name="' + field.name + '"]')` wont' work because it will look for `[name=ContactForm[email]]` and it doesn't like the double [ ].

**Comment by cferdinandi** [comment]
The issue is only with IDs and `querySelector()` for the error messages. The inputs themselves seem to be fine. I pulled in your escape function in https://github.com/cferdinandi/bouncer/releases/tag/v1.2.1, gave you attribution, and only use it in `getFieldID()`. 

This carries over to all the places where it's used without have to include it explicitly, keeping the code more DRY. Thanks for your help here!

**Comment by smcyr** [comment]
I tried with the new version (1.2.2) and I have the same problem as before. The error message is created each time you validate as you can see in my screenshot. Thanks
![validation-errors](https://user-images.githubusercontent.com/664920/49254240-bb056f00-f3f6-11e8-99f4-b9169d7bf729.jpg)

**Comment by cferdinandi** [comment]
Please provide a reduced test case

**Comment by smcyr** [comment]
You can test with this html file and click multiple times on submit without filling anything. And after that, try filling the radio buttons and email input. You can see that there are multiple error messages and that they don't disappear. Thanks
```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Test Validation</title>
        <style>
            .error {
                border-color: red;
                color: red;
            }

            .error + label {
                color: red;
            }

            .error-message {
                color: red;
            }
        </style>
    </head>
    <body>
        <form>
            <input id="category-1" type="radio" required="required" name="ContactForm[category]" value="category-1"><label for="category-1">Category 1</label>
            <input id="category-2" type="radio" required="required" name="ContactForm[category]" value="category-2"><label for="category-2">Category 2</label>
            <input id="category-3" type="radio" required="required" name="ContactForm[category]" value="category-3"><label for="category-3">Category 3</label>
            <br>
            <input type="email" required="required" name="ContactForm[email]" placeholder="Email">
            <br>
            <button>Submit</button>
        </form>

        <script src="https://cdn.jsdelivr.net/gh/cferdinandi/bouncer/dist/bouncer.polyfills.min.js"></script>
        <script>
            var validate = new Bouncer('form', {
                messageAfterField: false
            });
        </script>
    </body>
</html>
```

**Comment by cferdinandi** [comment]
The CDN hasn't flushed it's cache yet, but when it does, v1.2.3 should finally address this. Reduced test case: https://codepen.io/cferdinandi/pen/rQoxyM

Also, thank you so much for your help and for providing a reduced test case to work with!

**Comment by cferdinandi** [comment]
And CDN now has the latest version if you want to check the demo

**Comment by smcyr** [comment]
It works now, thanks!
