### ISSUE TITLE
Checkbox group validation works for only one of the group

### ISSUE THREAD

**Issue by smcyr** [cferdinandi/bouncer#17]
See this test case and click on submit without filling anything. There should be 3 error messages (like native validation) but there is only 1. If you check one, the error message disappear, but the other two checkboxes still don't have error messages and if you check them too, they still have the error css class. Thanks!
```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Test Validation</title>
        <style>
            .error {
                border-color: red;
                color: red;
            }
            .error + label {
                color: red;
            }
            .error-message {
                color: red;
            }
        </style>
    </head>
    <body>
        <form>
            <input id="category-1" type="checkbox" required="required" name="category[]" value="category-1"><label for="category-1">Category 1</label>
            <input id="category-2" type="checkbox" required="required" name="category[]" value="category-2"><label for="category-2">Category 2</label>
            <input id="category-3" type="checkbox" required="required" name="category[]" value="category-3"><label for="category-3">Category 3</label>
            <br>
            <button>Submit</button>
        </form>
        <script src="https://cdn.jsdelivr.net/gh/cferdinandi/bouncer/dist/bouncer.polyfills.min.js"></script>
        <script>
            var validate = new Bouncer('form', {
                messageAfterField: false
            });
        </script>
    </body>
</html>
```

**Comment by cferdinandi** [comment]
Good catch! I completely forgot that checkbox groups were a thing. Fixed with v1.2.4. Demo here (as soon as the CDN cache flushes): https://codepen.io/cferdinandi/pen/KrbBBr

**Comment by smcyr** [comment]
It's better, but if you comment out the javascript, Firefox or Chrome validate each checkbox independtly. So, it's different from the radio buttons where just one is required. Also, see this pen:
https://codepen.io/anon/pen/vQvaPZ
The first and the last are required, but the middle one still has the error class. Just the first one and the last one should be validated in this case. And if you check the first one, the last one should still have the error, to be consistent with the browser validation.
Thanks!

**Comment by smcyr** [comment]
Yes, the validation in the case of checkbox groups should be independent for each checkbox as if they had different name="".

**Comment by cferdinandi** [comment]
Ok, so... forgive me but, wasn't that the original behavior? Validate each checkbox on its own?

**Comment by cferdinandi** [comment]
No, you're right, I just worked backwards to see what was happening in older versions. Sorry! Coffee hasn't quite kicked in yet today! ☕️😂

I'll get this sorted. Each checkbox should have its own error message and validation, with the error message appearing before/after the label instead of the input.

**Comment by smcyr** [comment]
Ahah, no problem, I like your library and wanted to use it instead of a bloated jQuery plugin :) Thanks!

**Comment by cferdinandi** [comment]
Alright, officially fixed with v1.2.5: https://codepen.io/cferdinandi/pen/KrbBBr

**Comment by smcyr** [comment]
Thanks, but it seems that the logic was also implemented for radio buttons groups, but those are different, there must be only one error message for the group.
https://codepen.io/smcyr/pen/NEJLyO
Check the behavior with or without javascript.
Thanks!

**Comment by cferdinandi** [comment]
It shouldn't have been. Hmmm

**Comment by cferdinandi** [comment]
Sigh, ok. Hopefully finally have this nailed down. v1.3.0 https://codepen.io/cferdinandi/pen/KrbBBr

**Comment by smcyr** [comment]
Seems to be working perfectly, thanks!
