### ISSUE TITLE
Be able to choose error message location

### ISSUE THREAD

**Issue by smcyr** [cferdinandi/bouncer#18]
Hi, still me :D
See this pen:
https://codepen.io/smcyr/pen/Krbxow
In this particular implementation, I would like the error message to be positioned below the 3 radio buttons (which are hidden and displayed as grey blocks) which is not the case.
Maybe there could be a data attribute like `data-error-message="category"` where you specify the input name inside. This data attribute could be added to a <div> anywhere on the page and would overwrite the default position for the error message placement.
Thanks!

**Comment by smcyr** [comment]
It could just be an event on the "createError" function where I could return an element to use instead. Or in the options of bouncer, there could be an option callback "createError" where I can write the function I want.

**Comment by cferdinandi** [comment]
So, you may still want this feature, but you can achieve the layout you shared (with better accessibility and proper semantics) and still get the error message where you want it.

https://codepen.io/cferdinandi/pen/PxXyMG

Labels should always have content in them or screen reader users won't know what the radio button is for. And by styling the label itself rather than wrapping it in another element, you can get the error message to appear after the entire group.

**Comment by smcyr** [comment]
Good point that I should at least have text into the label. But in my case, for the website I am working on, I have HTML inside the label (<h3>,<ul> and <p>), so I did it this way, because I don't think block elements are allowed inside <label> elements. Here is an updated pen:
https://codepen.io/smcyr/pen/Krbxow
I added <h3> and <ul>. Also some text inside labels with a negative text-indent.

**Comment by smcyr** [comment]
Here is probably a better version with the label just after the input:

https://codepen.io/smcyr/pen/OardML

**Comment by cferdinandi** [comment]
Just wanted to note intent to implement this feature. I'll try to work on it this week.

**Comment by cferdinandi** [comment]
Alright, added with v1.3.0: https://github.com/cferdinandi/bouncer#error-message-location

**Comment by smcyr** [comment]
I tried implementing the new setting data-bouncer-target and I have this error: "NotFoundError: Node was not found"
https://codepen.io/smcyr/pen/OardML

**Comment by cferdinandi** [comment]
Good catch. Patched in v1.3.1: https://codepen.io/cferdinandi/pen/gQEyKv

**Comment by smcyr** [comment]
Thank you! All is working perfectly for my use case now!
