### ISSUE TITLE
Function to validate subset of fields (e.g. a fieldset)

### ISSUE THREAD

**Issue by Ciantic** [cferdinandi/bouncer#21]
I have a long form, a really long in fact.

I'd like to validate it in parts, e.g. when custom button at the end of fieldset is clicked it validates that fieldset (I'm not using `<fieldset>` element but a `<section>` but the point is same).

Currently I'm doing it like this, which works just fine, but I have to re-implement some of the focus stuff:

```javascript
    var bouncer = new Bouncer("form", {
        disableSubmit: true
    });
    form.find("button.next").click(function() {
        var section = $(this).parent();
        var isValid = true;
        var jumpToError = function(event) {
            window.scrollTo(0, event.target.offsetTop);
            event.target.focus();
        };
        // Notice jQuery "one" callback hook
        section.one("bouncerShowError", jumpToError);
        section.find(":input").each(function() {
            var result = bouncer.validate($(this).get(0));
            if (result && !result.valid) {
                isValid = false;
            }
        });
        section.off("bouncerShowError", jumpToError);
        if (!isValid) {
           // Hide current section, show next section code snipped
        }
    });
```

Apologies for the jQuery in my example, but the point should be clear.

What I would like to have is a API such as:

```
    var bouncer = new Bouncer("form", {
        disableSubmit: true
    });
    bouncer.validate(document.querySelector("fieldset.first")); 
```

Which would validate all fields in the fieldset, do all the necessary other stuff, not sure what that is.

This is not a very important feature, but I gather someone else could make use of it too.

**Comment by cferdinandi** [comment]
Great use case, and not a bad idea. I just added the `validateAll()` method with https://github.com/cferdinandi/bouncer/releases/tag/v1.4.0.

Docs on how it works here: https://github.com/cferdinandi/bouncer#validateall
