### ISSUE TITLE
Adding fieldset inside form prevents validation from working

### ISSUE THREAD

**Issue by atsea** [cferdinandi/bouncer#3]
Hey Chris,

Using your demo code I added a fieldset wrapper around the form field div containers. When I click submit, validation never completes (no error styles, error text). When fieldset is removed everything works as intended.
One error shows in DevTools :

`TypeError: e.value is undefined[Learn More] _display:121:1
	u http://fiddle.jshell.net/_display/:121:1
	f http://fiddle.jshell.net/_display/:121:7204
	window.onload/</</l.validate http://fiddle.jshell.net/_display/:121:9042
	m/n< http://fiddle.jshell.net/_display/:121:9427
	filter self-hosted:318:17
	m http://fiddle.jshell.net/_display/:121:9362
  `

**Test case:** [https://codepen.io/finstah/pen/vQymoB](https://codepen.io/finstah/pen/vQymoB)

**Comment by robsonsobral** [comment]
Two options:

- to have a list of form fields which can be validated to test against the `form.elements`;
- ~~to use `(field.value || {}).length` instead of `field.value.length`.~~
- to use `(field.value || []).length` instead of `field.value.length`.

**Comment by cferdinandi** [comment]
I think that should be an array, not an object (objects don't have length as a property), but good catch!

I'll update the code soon!

**Comment by atsea** [comment]
No worries Chris. Robson, nice solution

**Comment by cferdinandi** [comment]
Property fixed here: https://github.com/cferdinandi/bouncer/releases/tag/v1.0.5
