### ISSUE TITLE
Password strength and pls Submit another usefull customValidations 

### ISSUE THREAD

**Issue by riiccardo** [cferdinandi/bouncer#32]
hey @cferdinandi thanks for ur lightweight package  😍 

can we have better documentation in [demoLink](https://cferdinandi.github.io/bouncer/) ?

some usefull validation

1.Password strength
2. shorter than or bigger than 6 for example

another question is how to validate one input one by one
if valid addClass of success ( for example green border ) for 3 sec user find out input isValid 

and how to use `data-bouncer-message` for normal input like `type="text"`

Regards <3 👍

**Comment by cferdinandi** [comment]
Hi there, and thanks for the kudos!

## Demo & Validation

The demo is intended purely to show what Bouncer looks like versus browser default validation (it includes almost no custom patterns, etc.).

Password length could be validated using [the browser-native `minlength` and `maxlength` attributes](https://github.com/cferdinandi/bouncer#min-and-max-length).

I unfortunately cannot provide support around custom patterns for things like password strength, etc. However, there are lots of sites around the web that offer regex patterns for various things you might find useful.

## Validation Successful

I can add a custom event for successfully validated fields. I'll create a new issue for this as a feature request.

## `data-bouncer-message`

This works with any field type that has a custom pattern. There's a PR in place to support this for any validation error type that I intend to merge.

https://github.com/cferdinandi/bouncer/pull/29
