### ISSUE TITLE
$_POST[ 'submitted '] is missing

### ISSUE THREAD

**Issue by mokorana** [cferdinandi/bouncer#36]
The input element with type='submit' name='submitted' is not present in the array $_POST. Guess its because the validation on the submit-event. Is there any easy solution?

**Comment by cferdinandi** [comment]
@mokorana Is there any way for me to replicate this issue?

The form never gets submitted if it fails validation. If it passes, Bouncer triggers the native form submit event (with page reload) and sends the entire form back to the server. 

Unless you're using the `disableSubmit` option, this shouldn't happen.

**Comment by mokorana** [comment]
@cferdinandi replication is difficult I gues. But I will show you what I done. If I don't load the bouncer.js everything works fine.

`
<form method="post" action="">
  <input type="email" name="email">
  <button type="submit" name="submitted">Submit</button>
</form>
`
print_r( '$_POST' );

just outputs:
Array ( [email] => test@email.de )

**Comment by cferdinandi** [comment]
Ah, so it appears this is a side effect of using `form.submit()` to submit the form if it validates: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit

Unfortunately, that means I have no fix for it.
