### ISSUE TITLE
Error message injection fails if DOM is modified after init.

### ISSUE THREAD

**Issue by matthewmcvickar** [cferdinandi/bouncer#37]
I am using another JS library to create the 'floating labels' effect, and it interferes with the functionality of Bouncer because it wraps the fields of the form in their own `<div>` when it initiates. This confuses Bouncer's error message injection, causing an error when it tries to find the `parentNode`: `Uncaught TypeError: Cannot read property 'parentNode' of null`

Oddly, setting `messageAfterField: false` option is a workaround for this.

See both the error and the workaround in this codepen:

**Test case:** https://codepen.io/matthewmcvickar/pen/omzvGd

**Comment by fiznool** [comment]
As another workaround you could use the [data-bouncer-target](https://github.com/cferdinandi/bouncer#error-message-location) along with a hard-coded HTML tag to specify where the error message should be rendered.

**Comment by cferdinandi** [comment]
I would use @fiznool's approach above ~~^
