### ISSUE TITLE
validation of a checkbox group.

### ISSUE THREAD

**Issue by frphilippe** [cferdinandi/bouncer#40]
Bonjour,
I would like to validate a checkbox group with the latest version of bouncer.js 1.4.3 as the following CodePen:
https://codepen.io/anon/pen/KENaor
There must be at least one or more boxes checked but not necessarily all with a single error message.
Is it possible?
In what way.
Thank you for your reply.

**Comment by cferdinandi** [comment]
Possible duplicate? https://github.com/cferdinandi/bouncer/issues/17

Let me know if its not and I'll reopen.

**Comment by frphilippe** [comment]
Bonjour,
I was aware of this conversation before contacting you but the operation I want will work with version 1.2.4.
 https://codepen.io/anon/pen/KENaor.
But with the latest version 1.4.2 for a group of checkboxes that have the same attribute name there is an error message by Checkbox and all checkboxes in the group must be validated.
https://codepen.io/anon/pen/NJdWJz
Is it possible to find the operation of checkbox group validation (same attribute name) of version 1.2.4 with version 1.4.2?
Thank you.

**Comment by cferdinandi** [comment]
Apologies, but I'm not 100% sure I understand the desired behavior. Can you clarify?

**Comment by frphilippe** [comment]
I have a group of 12 checkboxes with the same attributename="Cours[]".
I would like to be able to validate the entire group if one or more checkboxes are selected.
If no checkbox is selected, only one error message will be required.
Which corresponds to the operation of the version 1.2.4.
Example: https://codepen.io/anon/pen/KENaor.

But we can not find this operation with the latest version 1.4.2 
Example: https://codepen.io/anon/pen/NJdWJz. Checkbox validations are independent with an error message by checkbox.

Is it possible to find this operation with the version 1.4.2?
Thank you.

**Comment by robertodevivo** [comment]
This is exactly the issue i'm having using 1.4.3. Checkboxes that are part of the same checkbox group (i.e. they have the same value in the name attribute) are validated separately and not as a whole in this version of Bouncer. 

Desired behaviour is that checkboxes with the same name attribute are treated as a group. This means that if a single checkbox is ticked within this group it will be valid as the requirement is met.

**Comment by cferdinandi** [comment]
Digging into this a little bit more, that's not consistent with how browsers treat checkboxes natively or what the expectation for checkboxes are.

A more robust form validator might better fit your needs around this.

**Comment by iamkeir** [comment]
Just for future reference, for anyone struggling with this, you can make Bouncer work to validate a group of checkboxes where at least one is required: https://codepen.io/iamkeir/pen/jgzOJr?editors=1010

The downside is you cannot use the `required` attribute, as we need to suppress the individual required validation.

@cferdinandi I'd definitely welcome if you think this could be done more simply :)

**Comment by iamkeir** [comment]
That said, the above starts outputting multiple error messages if you assign values to the checkboxes... which seems odd: https://codepen.io/iamkeir/pen/wVmKyV?editors=1010

Possible bug? Related to #17?

**Comment by iamkeir** [comment]
Ref: #47

**Comment by xini** [comment]
I agree. A checkbox group with the same name attribute should be validated as a whole. 
I think the multiple messages are related to the changes in #17 which includes the field value in the id in https://github.com/cferdinandi/bouncer/commit/b450b24bbaa9c01941abd7a1e80e1e9723c61457#diff-0825e4e8b268ffd0956559ebd7130bd7R407. 
@iamkeir Have you found a work-around for this in the meantime?

**Comment by iamkeir** [comment]
@xini I can't recall to be honest - I think I may have eventually used an alternative library such as [ParsleyJS](https://parsleyjs.org/).

**Comment by xini** [comment]
> @xini I can't recall to be honest - I think I may have eventually used an alternative library such as [ParsleyJS](https://parsleyjs.org/).

Thanks. Yeah. I just really don't want to use jQuery...

**Comment by croxton** [comment]
In case anyone runs across this, here's one way to validate a set of checkboxes:
https://codepen.io/croxton/pen/wvymNry
