### ISSUE TITLE
Method typo

### ISSUE THREAD

**Issue by maxpower011** [cferdinandi/bouncer#41]
No need for fork or test case, the problem is a simple typo in your code. the .destroy function fails because your custom wrapper forEach is mis-spelled as formEach (see below for a snippet of your code). The typo causes destroy to fail.

`var removeAllErrors = function (selector, settings) {
		forEach(document.querySelectorAll(selector), function (form) {
			formEach(form.querySelectorAll('input, select, textarea'), function (field) {
				removeError(field, settings);
			});
		});
	};`

thanks

**Comment by cferdinandi** [comment]
DOH! Thanks for this! Just pushed a fix.
