### ISSUE TITLE
bouncerFormValid doesn't fire until re-submission of form

### ISSUE THREAD

**Issue by iamkeir** [cferdinandi/bouncer#44]
The `bouncerFormValid` event only fires once all fields are valid *AND* you re-submit the form. Expected behaviour would be to fire event as soon as fields are valid, as per `bouncerFormInvalid`.

**Test case:** https://codepen.io/iamkeir/pen/PMRvzp

**Comment by cferdinandi** [comment]
Both `bouncerFormInvalid` and `bouncerFormValid` only fire when the form is submitted.

The intent with both is to let you know that the user has (re)submitted the form and indicate that state of overall validation.

Perhaps you're thinking of `bouncerShowError`, which emits whenever an individual field has an error.

**Comment by iamkeir** [comment]
How strange, I thought I tested this in the codepen... no worries, thanks.
