### ISSUE TITLE
aria-required

### ISSUE THREAD

**Issue by awgul** [cferdinandi/bouncer#45]
Hey,

Is it possible to look for `aria-required`.
I have such a situation that there is no `required` but is `aria-required` and I can't change the HTML code.
Or I will build a custom validation then.

**Comment by cferdinandi** [comment]
It's possible, but it's not something I'd add support for. Bouncer is intended to extend native form validation, which means using the native `require` attribute.

**Comment by awgul** [comment]
OK.
