### ISSUE TITLE
Reset validation

### ISSUE THREAD

**Issue by St-Permiakov** [cferdinandi/bouncer#48]
There is no way of resetting validation alongside form itself.
Or at least I haven't found one.
So if you have a form, say, in a popup, you want to reset it everytime user closes it. But errors still remain.

A method to reset all errors and validated fields will be magnificent.

**Comment by cferdinandi** [comment]
I believe you're looking for [the `destroy()` method](https://github.com/cferdinandi/bouncer#destroy). You can reinstantiate Bouncer when the popup opens.
