### ISSUE TITLE
scroll to input with error does not respect sticky header

### ISSUE THREAD

**Issue by richgwil** [cferdinandi/bouncer#6]
Hi, not sure if right way to submit...
seems that the scroll to input with error doesn't take into account sticky header, i.e. if form is longer than viewport, and error field is above top of vp, the positioning is under sticky header.
I hope that make sense.
will try with position:fixed and see if the same.
many thanks

edit: 4 minutes later. Sorry checked code and see the error field has focus set. Not sure what you can do. Will have a think myself. Cheers

edit: 10 minutes later. If error focus was turn offable in options, could handle scrolling and focus in eventlistener on custom event?

**Comment by cferdinandi** [comment]
This is all driven by `field.focus()`. The `focus()` method brings the first field with an error into focus on form submission, which in most browsers also causes the window to jump to that field's position on the page.

You *should* be able to make use of [a custom Bouncer event](https://github.com/cferdinandi/bouncer#custom-events) to address this, but I can see some issues with that approach currently. Specifically...

- There is no `bouncerFormInvalid` event to check when the whole form fails.
- You could use `bouncerShowError`, but that will fire for every single error, making it unreliable to use.

I'm going to make a few quick updates to the event emitters to make this more versatile and fit your use case. Will update you soon.

**Comment by robsonsobral** [comment]
A little suggestion: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by richgwil** [comment]
@robsonsobral That was what I was thinkig of (actually was thinking of Chris's smooth-scroll which I'm using on the site already)
@cferdinandi Thanks Chris, that's what I was hoping for. Loving your work (vanillajstoolkit, smooth-scrolll, et-al. learnt a huge amount from you), will await update :)

**Comment by robsonsobral** [comment]
The center of screen is (almost) always the best place to scroll to, specially on mobile.

**Comment by cferdinandi** [comment]
@robsonsobral that solution doesn't guarantee the field will be visible, depending on how much of the viewport the header takes up. I'm not even sure it guarantees that the header won't overlap over it.

**Comment by robsonsobral** [comment]
@cferdinandi , the reason for my "almost".

**Comment by cferdinandi** [comment]
@richgwil Alright, just pushed a new version (1.1.0) with a new custom event: `bouncerFormInvalid`.

When that event fires, you want to:

1. Calculate the current position on the page.
2. Calculate the height of your sticky header.
3. Add them together (plus maybe a little extra for some padding).
4. Use `window.scrollTo()` to change the position on the page.

Here's an example...

```js
document.addEventListener('bouncerFormInvalid', function (event) {

	// The current position on the page
	var pos = window.pageYOffset;
	
	// Get the height of the fixed header
	var header = document.querySelector('#my-header');
	var styles = window.getComputedStyle(header);
	var height = parseInt(styles.height, 10) + parseInt(styles.paddingTop, 10) + parseInt(styles.paddingBottom, 10) + parseInt(styles.marginTop, 10) + parseInt(styles.marginBottom, 10);

	// Make sure the height is less greater than the current position
	if (pos < height) return;

	// Scroll a bit
	// This example uses a buffer of 20px
	window.scrollTo(0, pos + height + 20);

}, false);
```

**Comment by richgwil** [comment]
been offline.
amazing, thankyou, will implement today :)
