### ISSUE TITLE
Hidden/not visible fields are validated

### ISSUE THREAD

**Issue by lbd01** [cferdinandi/bouncer#67]
Currently if a form contains a not visible field (e.g. with css display: none) it will get validated.
This creates a problem with template elements in DOM which are used to create new, visible items on webpage.
Possible options:
- skip from validation fields that are not visible (e.g. el.type!='hidden' && el.offsetParent === null)  
- allow to manualy remove errors (like the removeError function from the prev lib: https://github.com/cferdinandi/validate)

**Comment by cferdinandi** [comment]
Bouncer's main goal is to emulate native browser validation behavior. A hidden field in a form with validation on it (a `required` attribute, for example) will trigger browser validation and prevent a form from being submitted just like Bouncer does.

My recommendation would be to keep the template outside the form, or add the validation field when cloning.

**Comment by lbd01** [comment]
Moving the templates outside the form is an option, but would require some re-engineering on my side. A quick and dirty workaround without bouncer changes is to do sth like this:

```
function isHidden(el) {
    return (el.type!='hidden' && el.offsetParent === null)
}

var errors = bouncer.validateAll(form);
var errorCount = 0;
for (var i=0;i<errors.length;++i) {
    if (!isHidden(errors[i])) ++errorCount;
}

if (errorCount>0) //we have a problem
```
