### ISSUE TITLE
IE11 error with email pattern

### ISSUE THREAD

**Issue by awgul** [cferdinandi/bouncer#7]
Hey,

When having an email type filed on IE11 I get this error on keypress or submit:
SCRIPT5017: Syntax error in regular expression
bouncer.js (199,3)

**Comment by cferdinandi** [comment]
Aww crap. This appears to be caused by IE11 and lower not allowing anything but a string as the first argument in `new RegExp()`.

I'll get this fixed as soon as I can. Thanks for opening this issue.

**Comment by cferdinandi** [comment]
Note for me: pull in RegEx patterns from https://github.com/cferdinandi/bouncer/pull/2/files

**Comment by cferdinandi** [comment]
Ok, fixed with v1.1.2. Thanks!
