### ISSUE TITLE
Some suggestions for validating rules

### ISSUE THREAD

**Issue by awgul** [cferdinandi/bouncer#8]
Hey,

How about:

1. Check Password Confirmation - so compare 2 fields for example like `data-bouncer-compare="password-check"` or something like that.

2. Checkboxes - how to check if some amount is checked like at least 3?
Some reference:
http://www.formvalidator.net/#default-validators_checkboxgroup

**Comment by cferdinandi** [comment]
These are great! I'm still not sure from a product direction standpoint if I want to make this a full-fledged validator or treat it as simple augmentation on top of native HTML5 validation.

I suspect I'll want to incorporate stuff like this, but... I'm not sure yet.

I'm thinking there way even be a way to extend Bouncer with custom validation properties and stuff, and that may be the better way to go.

**Comment by awgul** [comment]
I've been generally using http://www.formvalidator.net/

But I like yours more.
Simpler, lighter, no dependency.

Generally I can test for the checkboxes or password confirmation using some custom code.
But then I would need some method like `bouncer.invalidate(field, errorMsg)`, to show the error, but then how to check if it is valid on change (not submit) - for example as for the password confirmation?
Just thinking.

**Comment by cferdinandi** [comment]
Quick update: I've got this working over on the [feature branch](https://github.com/cferdinandi/bouncer/tree/feature). 

Just working up some documentation, and will release shortly. Only added 1kb minified, so really happy with how this turned out!

**Comment by cferdinandi** [comment]
And... officially supported: https://github.com/cferdinandi/bouncer/releases/tag/v1.2.0

**Comment by cferdinandi** [comment]
For propriety, here are the docs: https://github.com/cferdinandi/bouncer#custom-validation-types

**Comment by awgul** [comment]
Great!
Thank you.
I will have a look tomorrow.
